### ISSUE TITLE
hi, do you have a discord server for your mod? If not, I invite you to mine. 

### ISSUE THREAD

**Issue by PLsubfarm61** [racti2037/Real-Military-Techic-mod#3]
https://discord.gg/7SSAupjxeD
![QR_URL_20230415_134039](https://user-images.githubusercontent.com/122689877/232241892-30ff77f2-defc-4857-bde6-2c21094732c2.png)

**Comment by racti2037** [comment]
yes i create them, https://discord.gg/4WjGShep
